repos:
- repo: local
  hooks:
  - id: editorconfig-checker
    name: Verify Editorconfig
    language: system
    entry: editorconfig-checker
    types: [text]
  - id: nixpkgs-fmt
    name: Verify Nix Formatting
    language: system
    entry: nixpkgs-fmt --check
    types: [nix]
  - id: codespell
    name: Check Spelling
    language: system
    entry: codespell
    types: [text]
  - id: nix-flake-check
    name: Run Nix Flake Checks
    language: system
    entry: nix flake check --no-build --show-trace
    types: [nix]
    pass_filenames: false
